services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: <desired-address>
    environment:
      GATEWAY_SYSTEM_NAME: <desired-address>
    networks:
      - default
      - proxy

  database:
    labels:
      traefik.enable: "true"
      traefik.hostname: postgres
    networks:
      - default
      - proxy
  # Uncomment the following lines to enable pgAdmin
  # pgadmin:
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.postgres-template-pgadmin.entrypoints: "web"
  #     traefik.http.routers.postgres-template-pgadmin.rule: "Host(`postgres-template-pgadmin.localtest.me`)"
  #     traefik.http.services.postgres-template-pgadmin.loadbalancer.server.port: "80"
  #   networks:
  #     - default
  #     - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
