services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.ignition-template.entrypoints: "web"
      traefik.http.routers.ignition-template.rule: "Host(`ignition-template.localtest.me`)"
      traefik.http.services.ignition-template.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: ignition-template
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: ignition-template.localtest.me
    networks:
      - default
      - proxy

  database:
    labels:
      traefik.enable: "true"
      traefik.http.routers.postgres-template-database.entrypoints: "web"
      traefik.http.routers.postgres-template-database.rule: "Host(`postgres-template-database.localtest.me`)"
      traefik.http.services.postgres-template-database.loadbalancer.server.port: "5432"
    networks:
      - default
      - proxy
  # Uncomment the following lines to enable pgAdmin
  # pgadmin:
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.routers.postgres-template-pgadmin.entrypoints: "web"
  #     traefik.http.routers.postgres-template-pgadmin.rule: "Host(`postgres-template-pgadmin.localtest.me`)"
  #     traefik.http.services.postgres-template-pgadmin.loadbalancer.server.port: "80"
  #   networks:
  #     - default
  #     - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy